openapi: 3.2.0
info:
  title: ⚙️ API specifications Ping API
  description: Dotfile public API documentation
  version: v1
  contact: {}
servers:
- url: https://api.dotfile.com
  description: Production environment
security:
- DotfileAPIKey: []
tags:
- name: Ping
paths:
  /v1/ping:
    get:
      operationId: ping-ping
      summary: Ping the API
      description: 'This endpoint allows you to test your API key.


        ---


        #### See also

        Learn more about Authentication'
      parameters: []
      responses:
        '200':
          description: 'Ping successful


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
      tags:
      - Ping
components:
  schemas:
    Ping:
      type: object
      properties:
        workspace_name:
          type: string
      required:
      - workspace_name
  securitySchemes:
    DotfileAPIKey:
      type: apiKey
      in: header
      name: X-DOTFILE-API-KEY
      description: Configure your api key in the Workspace settings
x-uploaded-at: '2026-08-14T14:05:07.336Z'
x-commit-sha: f460fa65a5cc33cf4211bbcee7818f93d5b9e8de
